version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: dashlite-app
        working_dir: /var/www
        volumes:
            - .:/var/www
        depends_on:
            - db
            - redis
        environment:
            - DB_CONNECTION=pgsql
            - DB_HOST=db
            - DB_PORT=5432
            - DB_DATABASE=dashlite
            - DB_USERNAME=user
            - DB_PASSWORD=password
            - REDIS_HOST=redis
            - REDIS_PASSWORD=secret
            - CACHE_DRIVER=redis
            - SESSION_DRIVER=redis
        networks:
            - dashlite-network

    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost/health" ]
            interval: 30s
            retries: 3
            start_period: 10s
            timeout: 10s
        volumes:
            - ./:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - dashlite-network

    db:
        image: postgres:17
        container_name: dashlite-db
        environment:
            POSTGRES_DB: dashlite
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
        volumes:
            - postgres-data:/var/lib/postgresql/data

        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U user -d dashlite" ]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 10s
        networks:
            - dashlite-network

    redis:
        image: redis:8
        container_name: dashlite-redis
        command: [ "redis-server", "--requirepass", "secret" ]
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 30s
            retries: 3
            start_period: 10s
            timeout: 10s
        networks:
            - dashlite-network

volumes:
    postgres-data:

networks:
    dashlite-network:
        driver: bridge

