name: Build and push docker image

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get Git commit hash
        run: echo "GIT_COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/dashlite:${{ env.GIT_COMMIT_HASH }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/dashlite:${{ env.GIT_COMMIT_HASH }}
